### ISSUE TITLE
eosgi plugin elevate fails on 32 bit Windows 7

### ISSUE THREAD

**Issue by attila-czabany** [everit-org/eosgi-maven-plugin#1]
On 32 bit Windows7 systems, the mvn clean eosgi:dist command produces the following error:

[WARNING] Could not create symbolic links. As this is a windows system trying with higher privileges.
[INFO] We have a 32 bit operating system so copying the 32 bit elevate exe file
[INFO] Running: [C:\Users\ATTILA~1.CZA\AppData\Local\Temp\everit-linkFolder-6f002778-be60-4e06-ba17-751111516fdb\elevate
.exe, -wait, C:\Users\ATTILA~1.CZA\AppData\Local\Temp\everit-linkFolder-6f002778-be60-4e06-ba17-751111516fdb\dolinks.cmd
]
[ERROR] Could not run with elevated privileges
java.io.IOException: Cannot run program "C:\Users\ATTILA~1.CZA\AppData\Local\Temp\everit-linkFolder-6f002778-be60-4e06-b
a17-751111516fdb\elevate.exe": CreateProcess error=216, This version of %1 is not compatible with the version of Windows
 you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version
 of the program, and then contact the software publisher
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at org.everit.osgi.dev.maven.util.DistUtil.tryRunningWithElevate(DistUtil.java:309)
        at org.everit.osgi.dev.maven.util.DistUtil.createSymbolicLinks(DistUtil.java:215)
        at org.everit.osgi.dev.maven.DistMojo.resolveAndCopyArtifacts(DistMojo.java:312)
        at org.everit.osgi.dev.maven.DistMojo.execute(DistMojo.java:215)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.io.IOException: CreateProcess error=216, This version of %1 is not compatible with the version of Window
s you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) versio
n of the program, and then contact the software publisher
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:189)
        at java.lang.ProcessImpl.start(ProcessImpl.java:133)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1021)
        ... 25 more

This occurs only if the user executes the command as non-administrator. If the user opens a command-prompt as administrator, the mvn clean eosgi:dist command executes successfuly.

**Comment by Dannieib** [comment]
i don't get you sir. please explain more clearly.. thanks. did you mean i should open the android studio as an admin?

**Comment by balazs-zsoldos** [comment]
@Dannieib eosgi-maven-plugin does not work with symbolic links since 3.x, therefore it is not necessary to execute it with elevated rights on windows. If you are interested in this plugin, I suggest to use the most current version (4.1.3)

**Comment by Dannieib** [comment]
but will my android studio work properly?

**Comment by balazs-zsoldos** [comment]
@Dannieib eosgi-maven-plugin is a maven plugin to help the development of OSGi based applications. Android Studio is an IDE to develop Android based applications. Do you want to develop an OSGi based application on Android?

**Comment by Dannieib** [comment]
yeah, i really do want to... I need help

**Comment by balazs-zsoldos** [comment]
I suggest that you should write to the osgi-dev mailing list for an up-to-date tutorial (if there is any). With eosgi-maven-plugin you can speed up writing server-side apps. Packaging the app to Android needs at least 1-2 months of research (we did it ones and it took several months to make everything work).

**Comment by Dannieib** [comment]
okay.. put through the steps to go about this please... i'll so much be grateful sir.. if possible with screen shots

**Comment by balazs-zsoldos** [comment]
As a first step, I suggest to learn OSGi on that level that you could pass the [OSGi Developer](https://www.osgi.org/osgi-compliance/developer-certification/professional/) certificate. Without that, you are asking the impossible.

**Comment by Dannieib** [comment]
okay, please, we'll keep in touch, let me use this link
